liTest run scala.scalanative.junit.AssertThrowsTest started
liTest scala.scalanative.junit.AssertThrowsTest.test started
leTest scala.scalanative.junit.AssertThrowsTest.test failed: unexpected exception type thrown; expected:<java.lang.UnsupportedOperationException> but was:<java.lang.IllegalArgumentException>, took <TIME>
leCaused by: java.lang.IllegalArgumentException: Exception message
e2scala.scalanative.junit.AssertThrowsTest.test
ldTest scala.scalanative.junit.AssertThrowsTest.test finished, took <TIME>
liTest run scala.scalanative.junit.AssertThrowsTest finished: 1 failed, 0 ignored, 1 total, <TIME>
d
