ldTest run started
ldTest scala.scalanative.junit.AssertThrowsTest.test started
leTest scala.scalanative.junit.AssertThrowsTest.test failed: unexpected exception type thrown; expected:<java.lang.UnsupportedOperationException> but was:<java.lang.IllegalArgumentException>, took <TIME>
e2scala.scalanative.junit.AssertThrowsTest.test
ldTest scala.scalanative.junit.AssertThrowsTest.test finished, took <TIME>
ldTest run finished: 1 failed, 0 ignored, 1 total, <TIME>
d
