liTest run started
liTest scala.scalanative.junit.AssertThrows2Test.test started
leTest scala.scalanative.junit.AssertThrows2Test.test failed: This is the message: unexpected exception type thrown; expected:<java.lang.UnsupportedOperationException> but was:<java.lang.IllegalAccessException>, took <TIME>
e2scala.scalanative.junit.AssertThrows2Test.test
ldTest scala.scalanative.junit.AssertThrows2Test.test finished, took <TIME>
liTest run finished: 1 failed, 0 ignored, 1 total, <TIME>
d
