liTest run scala.scalanative.junit.ExceptionInConstructorTest started
liTest scala.scalanative.junit.ExceptionInConstructorTest.test started
leTest scala.scalanative.junit.ExceptionInConstructorTest.test failed: Exception while constructing the test class, took <TIME>
e2scala.scalanative.junit.ExceptionInConstructorTest.test
ldTest scala.scalanative.junit.ExceptionInConstructorTest.test finished, took <TIME>
liTest run scala.scalanative.junit.ExceptionInConstructorTest finished: 1 failed, 0 ignored, 1 total, <TIME>
d
